# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-15 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_ru', models.CharField(max_length=40)),
                ('word_en', models.CharField(max_length=40)),
                ('track_ru', models.FileField(blank=True, upload_to='uploads/words/')),
                ('track_en', models.FileField(blank=True, upload_to='uploads/words/')),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordListVal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort', models.IntegerField(default=0)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.Word')),
                ('word_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.WordList')),
            ],
        ),
    ]
