# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_word_wordlistval'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordlist',
            name='words',
            field=models.ManyToManyField(through='words.WordListVal', to='words.Word'),
        ),
    ]
